<!DOCTYPE html>
<html>
    <?php
        require 'head.php';
    ?>
<body>
    <?php
        require 'menu.php';
    ?>  
    <div class="content">Árvíztűrő tükörfúrógép
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis euismod justo quis lectus blandit iaculis. Aliquam quis porta odio. Cras ut nisl non ligula consectetur hendrerit eget eu nisl. Sed fermentum sed massa at consequat. Nunc consectetur, odio id consequat mattis, velit tortor lacinia est, id placerat lorem magna ut arcu. Integer augue risus, auctor non nibh quis, sodales fermentum tortor. Duis id tellus ac dolor luctus congue. Nullam non enim maximus, dapibus elit at, feugiat velit. Nullam laoreet malesuada mi sed malesuada. Etiam congue condimentum feugiat. Vestibulum fringilla volutpat arcu quis malesuada. Proin vitae leo vel dui tincidunt dapibus. In hac habitasse platea dictumst. Phasellus ac aliquam magna. Donec ut pretium mi.
Donec velit quam, dapibus et consequat a, accumsan eget ligula. In porta ornare urna, eu porttitor turpis tempor non. Integer faucibus non justo id tincidunt. Sed viverra ut felis non pharetra. Aenean eget vehicula dolor. Nunc consectetur eget enim sed commodo. Suspendisse at sem hendrerit lorem congue euismod.
Vestibulum facilisis tortor dictum quam varius, nec luctus lorem pretium. Nunc accumsan, enim sit amet facilisis lobortis, leo arcu efficitur justo, ut fermentum neque ipsum posuere tortor. Aenean congue quis lacus a convallis. Nullam euismod laoreet eros eget venenatis. Etiam mattis arcu consequat velit venenatis hendrerit vel ac tortor. Proin pretium metus turpis, ut elementum quam ullamcorper vitae. Nunc rutrum massa nibh, quis imperdiet eros fermentum quis. Phasellus velit magna, malesuada laoreet porta eget, rutrum eu augue. Vivamus elementum leo augue. Phasellus tempor mauris in nulla accumsan gravida. Pellentesque porta, leo id cursus scelerisque, arcu orci lacinia tellus, at aliquam lectus neque interdum nisi. Duis at sem viverra, aliquet dolor nec, hendrerit metus.
Nunc pellentesque egestas metus sed sodales. Ut nisl ligula, luctus sit amet viverra sed, bibendum a diam. Fusce est ante, pharetra venenatis velit placerat, scelerisque viverra turpis. Etiam efficitur faucibus ante, eget iaculis leo gravida ac. Integer sed urna pellentesque, lobortis turpis nec, facilisis massa. Vivamus vel facilisis metus, ac fringilla augue. Vivamus aliquet rutrum mauris, sed convallis lorem placerat a. Praesent ex justo, congue quis dolor id, convallis ornare nunc. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur eget maximus nisi. Nulla quis lorem rutrum, iaculis turpis sit amet, suscipit velit. Praesent vitae tincidunt metus. Integer velit risus, viverra nec mauris et, convallis dictum felis. Donec id volutpat mauris, tempus scelerisque quam.
Praesent ultrices aliquam gravida. Mauris a erat et ipsum tincidunt efficitur. Pellentesque sapien eros, malesuada ac posuere vel, dignissim interdum odio. Duis feugiat varius dolor, eu placerat magna malesuada eu. Nullam ac ultricies dui, nec scelerisque lorem. Ut in massa quis ante porttitor suscipit luctus et ipsum. Mauris non diam fringilla erat porta condimentum.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis euismod justo quis lectus blandit iaculis. Aliquam quis porta odio. Cras ut nisl non ligula consectetur hendrerit eget eu nisl. Sed fermentum sed massa at consequat. Nunc consectetur, odio id consequat mattis, velit tortor lacinia est, id placerat lorem magna ut arcu. Integer augue risus, auctor non nibh quis, sodales fermentum tortor. Duis id tellus ac dolor luctus congue. Nullam non enim maximus, dapibus elit at, feugiat velit. Nullam laoreet malesuada mi sed malesuada. Etiam congue condimentum feugiat. Vestibulum fringilla volutpat arcu quis malesuada. Proin vitae leo vel dui tincidunt dapibus. In hac habitasse platea dictumst. Phasellus ac aliquam magna. Donec ut pretium mi.
Donec velit quam, dapibus et consequat a, accumsan eget ligula. In porta ornare urna, eu porttitor turpis tempor non. Integer faucibus non justo id tincidunt. Sed viverra ut felis non pharetra. Aenean eget vehicula dolor. Nunc consectetur eget enim sed commodo. Suspendisse at sem hendrerit lorem congue euismod.
Vestibulum facilisis tortor dictum quam varius, nec luctus lorem pretium. Nunc accumsan, enim sit amet facilisis lobortis, leo arcu efficitur justo, ut fermentum neque ipsum posuere tortor. Aenean congue quis lacus a convallis. Nullam euismod laoreet eros eget venenatis. Etiam mattis arcu consequat velit venenatis hendrerit vel ac tortor. Proin pretium metus turpis, ut elementum quam ullamcorper vitae. Nunc rutrum massa nibh, quis imperdiet eros fermentum quis. Phasellus velit magna, malesuada laoreet porta eget, rutrum eu augue. Vivamus elementum leo augue. Phasellus tempor mauris in nulla accumsan gravida. Pellentesque porta, leo id cursus scelerisque, arcu orci lacinia tellus, at aliquam lectus neque interdum nisi. Duis at sem viverra, aliquet dolor nec, hendrerit metus.
Nunc pellentesque egestas metus sed sodales. Ut nisl ligula, luctus sit amet viverra sed, bibendum a diam. Fusce est ante, pharetra venenatis velit placerat, scelerisque viverra turpis. Etiam efficitur faucibus ante, eget iaculis leo gravida ac. Integer sed urna pellentesque, lobortis turpis nec, facilisis massa. Vivamus vel facilisis metus, ac fringilla augue. Vivamus aliquet rutrum mauris, sed convallis lorem placerat a. Praesent ex justo, congue quis dolor id, convallis ornare nunc. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur eget maximus nisi. Nulla quis lorem rutrum, iaculis turpis sit amet, suscipit velit. Praesent vitae tincidunt metus. Integer velit risus, viverra nec mauris et, convallis dictum felis. Donec id volutpat mauris, tempus scelerisque quam.
Praesent ultrices aliquam gravida. Mauris a erat et ipsum tincidunt efficitur. Pellentesque sapien eros, malesuada ac posuere vel, dignissim interdum odio. Duis feugiat varius dolor, eu placerat magna malesuada eu. Nullam ac ultricies dui, nec scelerisque lorem. Ut in massa quis ante porttitor suscipit luctus et ipsum. Mauris non diam fringilla erat porta condimentum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis euismod justo quis lectus blandit iaculis. Aliquam quis porta odio. Cras ut nisl non ligula consectetur hendrerit eget eu nisl. Sed fermentum sed massa at consequat. Nunc consectetur, odio id consequat mattis, velit tortor lacinia est, id placerat lorem magna ut arcu. Integer augue risus, auctor non nibh quis, sodales fermentum tortor. Duis id tellus ac dolor luctus congue. Nullam non enim maximus, dapibus elit at, feugiat velit. Nullam laoreet malesuada mi sed malesuada. Etiam congue condimentum feugiat. Vestibulum fringilla volutpat arcu quis malesuada. Proin vitae leo vel dui tincidunt dapibus. In hac habitasse platea dictumst. Phasellus ac aliquam magna. Donec ut pretium mi.
Donec velit quam, dapibus et consequat a, accumsan eget ligula. In porta ornare urna, eu porttitor turpis tempor non. Integer faucibus non justo id tincidunt. Sed viverra ut felis non pharetra. Aenean eget vehicula dolor. Nunc consectetur eget enim sed commodo. Suspendisse at sem hendrerit lorem congue euismod.
Vestibulum facilisis tortor dictum quam varius, nec luctus lorem pretium. Nunc accumsan, enim sit amet facilisis lobortis, leo arcu efficitur justo, ut fermentum neque ipsum posuere tortor. Aenean congue quis lacus a convallis. Nullam euismod laoreet eros eget venenatis. Etiam mattis arcu consequat velit venenatis hendrerit vel ac tortor. Proin pretium metus turpis, ut elementum quam ullamcorper vitae. Nunc rutrum massa nibh, quis imperdiet eros fermentum quis. Phasellus velit magna, malesuada laoreet porta eget, rutrum eu augue. Vivamus elementum leo augue. Phasellus tempor mauris in nulla accumsan gravida. Pellentesque porta, leo id cursus scelerisque, arcu orci lacinia tellus, at aliquam lectus neque interdum nisi. Duis at sem viverra, aliquet dolor nec, hendrerit metus.
Nunc pellentesque egestas metus sed sodales. Ut nisl ligula, luctus sit amet viverra sed, bibendum a diam. Fusce est ante, pharetra venenatis velit placerat, scelerisque viverra turpis. Etiam efficitur faucibus ante, eget iaculis leo gravida ac. Integer sed urna pellentesque, lobortis turpis nec, facilisis massa. Vivamus vel facilisis metus, ac fringilla augue. Vivamus aliquet rutrum mauris, sed convallis lorem placerat a. Praesent ex justo, congue quis dolor id, convallis ornare nunc. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur eget maximus nisi. Nulla quis lorem rutrum, iaculis turpis sit amet, suscipit velit. Praesent vitae tincidunt metus. Integer velit risus, viverra nec mauris et, convallis dictum felis. Donec id volutpat mauris, tempus scelerisque quam.
Praesent ultrices aliquam gravida. Mauris a erat et ipsum tincidunt efficitur. Pellentesque sapien eros, malesuada ac posuere vel, dignissim interdum odio. Duis feugiat varius dolor, eu placerat magna malesuada eu. Nullam ac ultricies dui, nec scelerisque lorem. Ut in massa quis ante porttitor suscipit luctus et ipsum. Mauris non diam fringilla erat porta condimentum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis euismod justo quis lectus blandit iaculis. Aliquam quis porta odio. Cras ut nisl non ligula consectetur hendrerit eget eu nisl. Sed fermentum sed massa at consequat. Nunc consectetur, odio id consequat mattis, velit tortor lacinia est, id placerat lorem magna ut arcu. Integer augue risus, auctor non nibh quis, sodales fermentum tortor. Duis id tellus ac dolor luctus congue. Nullam non enim maximus, dapibus elit at, feugiat velit. Nullam laoreet malesuada mi sed malesuada. Etiam congue condimentum feugiat. Vestibulum fringilla volutpat arcu quis malesuada. Proin vitae leo vel dui tincidunt dapibus. In hac habitasse platea dictumst. Phasellus ac aliquam magna. Donec ut pretium mi.
Donec velit quam, dapibus et consequat a, accumsan eget ligula. In porta ornare urna, eu porttitor turpis tempor non. Integer faucibus non justo id tincidunt. Sed viverra ut felis non pharetra. Aenean eget vehicula dolor. Nunc consectetur eget enim sed commodo. Suspendisse at sem hendrerit lorem congue euismod.
Vestibulum facilisis tortor dictum quam varius, nec luctus lorem pretium. Nunc accumsan, enim sit amet facilisis lobortis, leo arcu efficitur justo, ut fermentum neque ipsum posuere tortor. Aenean congue quis lacus a convallis. Nullam euismod laoreet eros eget venenatis. Etiam mattis arcu consequat velit venenatis hendrerit vel ac tortor. Proin pretium metus turpis, ut elementum quam ullamcorper vitae. Nunc rutrum massa nibh, quis imperdiet eros fermentum quis. Phasellus velit magna, malesuada laoreet porta eget, rutrum eu augue. Vivamus elementum leo augue. Phasellus tempor mauris in nulla accumsan gravida. Pellentesque porta, leo id cursus scelerisque, arcu orci lacinia tellus, at aliquam lectus neque interdum nisi. Duis at sem viverra, aliquet dolor nec, hendrerit metus.
    </div>
    <div class="footer">
        &#9400; Patrik Reizinger 	 2017
    </div>
</body>
</html>